# Form implementation generated from reading ui file 'C:\OneDrive\Vioprint\OneDrive - Vioprint\software projecten\Projectassisten2_0\gui\diffpanel.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


# [SECTION: Imports]
import logging
from PyQt6 import QtCore, QtGui, QtWidgets
logger = logging.getLogger(__name__)


# [END: Imports]
# [CLASS: Ui_DiffOptionsPanel]
class Ui_DiffOptionsPanel(object):
# [FUNC: setupUi]
logger.debug("setupUi() called")
    def setupUi(self, DiffOptionsPanel):
        DiffOptionsPanel.setObjectName("DiffOptionsPanel")
        self.vMain = QtWidgets.QVBoxLayout(DiffOptionsPanel)
        self.vMain.setObjectName("vMain")
        self.hPatch = QtWidgets.QHBoxLayout()
        self.hPatch.setObjectName("hPatch")
        self.cmbPatchType = QtWidgets.QComboBox(parent=DiffOptionsPanel)
        self.cmbPatchType.setObjectName("cmbPatchType")
        self.cmbPatchType.addItem("")
        self.cmbPatchType.addItem("")
        self.cmbPatchType.addItem("")
        self.cmbPatchType.addItem("")
        self.hPatch.addWidget(self.cmbPatchType)
        self.txtAnchor = QtWidgets.QLineEdit(parent=DiffOptionsPanel)
        self.txtAnchor.setObjectName("txtAnchor")
        self.hPatch.addWidget(self.txtAnchor)
        self.txtPatchLines = QtWidgets.QPlainTextEdit(parent=DiffOptionsPanel)
        self.txtPatchLines.setObjectName("txtPatchLines")
        self.hPatch.addWidget(self.txtPatchLines)
        self.btnApplyPatch = QtWidgets.QPushButton(parent=DiffOptionsPanel)
        self.btnApplyPatch.setObjectName("btnApplyPatch")
        self.hPatch.addWidget(self.btnApplyPatch)
        self.vMain.addLayout(self.hPatch)

        self.retranslateUi(DiffOptionsPanel)
        QtCore.QMetaObject.connectSlotsByName(DiffOptionsPanel)

# [END: setupUi]
logger.debug("retranslateUi() called")
# [FUNC: retranslateUi]
    def retranslateUi(self, DiffOptionsPanel):
        _translate = QtCore.QCoreApplication.translate
        DiffOptionsPanel.setWindowTitle(_translate("DiffOptionsPanel", "Opties diff bewerker"))
        self.cmbPatchType.setItemText(0, _translate("DiffOptionsPanel", "INSERT_AFTER"))
        self.cmbPatchType.setItemText(1, _translate("DiffOptionsPanel", "INSERT_BEFORE"))
        self.cmbPatchType.setItemText(2, _translate("DiffOptionsPanel", "REPLACE_AT"))
        self.cmbPatchType.setItemText(3, _translate("DiffOptionsPanel", "DELETE_AT"))
        self.txtAnchor.setPlaceholderText(_translate("DiffOptionsPanel", "Anker (regel of AN:...)"))
        self.btnApplyPatch.setText(_translate("DiffOptionsPanel", "Pas micro-patch toe"))
# [END: Ui_DiffOptionsPanel]
# [END: retranslateUi]
