# Form implementation generated from reading ui file 'C:\OneDrive\Vioprint\OneDrive - Vioprint\software projecten\Projectassisten2_0\gui\overigpanel.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


# [SECTION: Imports]
import logging
from PyQt6 import QtCore, QtGui, QtWidgets
logger = logging.getLogger(__name__)


# [END: Imports]
# [CLASS: Ui_OverigPanel]
class Ui_OverigPanel(object):
# [FUNC: setupUi]
logger.debug("setupUi() called")
    def setupUi(self, OverigPanel):
        OverigPanel.setObjectName("OverigPanel")
        self.vMain = QtWidgets.QVBoxLayout(OverigPanel)
        self.vMain.setObjectName("vMain")
        self.hTop = QtWidgets.QHBoxLayout()
        self.hTop.setObjectName("hTop")
        self.btnPrevDiff = QtWidgets.QPushButton(parent=OverigPanel)
        self.btnPrevDiff.setObjectName("btnPrevDiff")
        self.hTop.addWidget(self.btnPrevDiff)
        self.btnNextDiff = QtWidgets.QPushButton(parent=OverigPanel)
        self.btnNextDiff.setObjectName("btnNextDiff")
        self.hTop.addWidget(self.btnNextDiff)
        self.chkShowOnlyDiffs = QtWidgets.QCheckBox(parent=OverigPanel)
        self.chkShowOnlyDiffs.setObjectName("chkShowOnlyDiffs")
        self.hTop.addWidget(self.chkShowOnlyDiffs)
        self.chkIgnoreWhitespace2 = QtWidgets.QCheckBox(parent=OverigPanel)
        self.chkIgnoreWhitespace2.setObjectName("chkIgnoreWhitespace2")
        self.hTop.addWidget(self.chkIgnoreWhitespace2)
        self.chkIgnoreCase2 = QtWidgets.QCheckBox(parent=OverigPanel)
        self.chkIgnoreCase2.setObjectName("chkIgnoreCase2")
        self.hTop.addWidget(self.chkIgnoreCase2)
        self.txtSearch = QtWidgets.QLineEdit(parent=OverigPanel)
        self.txtSearch.setObjectName("txtSearch")
        self.hTop.addWidget(self.txtSearch)
        self.btnSearch = QtWidgets.QPushButton(parent=OverigPanel)
        self.btnSearch.setObjectName("btnSearch")
        self.hTop.addWidget(self.btnSearch)
        self.vMain.addLayout(self.hTop)
        self.hMiddle = QtWidgets.QHBoxLayout()
        self.hMiddle.setObjectName("hMiddle")
        self.lstDiffs = QtWidgets.QListWidget(parent=OverigPanel)
        self.lstDiffs.setObjectName("lstDiffs")
        self.hMiddle.addWidget(self.lstDiffs)
        self.vEditors = QtWidgets.QVBoxLayout()
        self.vEditors.setObjectName("vEditors")
        self.lblBlockContext = QtWidgets.QLabel(parent=OverigPanel)
        self.lblBlockContext.setObjectName("lblBlockContext")
        self.vEditors.addWidget(self.lblBlockContext)
        self.hEditors = QtWidgets.QHBoxLayout()
        self.hEditors.setObjectName("hEditors")
        self.txtLeft = QtWidgets.QPlainTextEdit(parent=OverigPanel)
        self.txtLeft.setReadOnly(True)
        self.txtLeft.setObjectName("txtLeft")
        self.hEditors.addWidget(self.txtLeft)
        self.txtRight = QtWidgets.QPlainTextEdit(parent=OverigPanel)
        self.txtRight.setObjectName("txtRight")
        self.hEditors.addWidget(self.txtRight)
        self.vEditors.addLayout(self.hEditors)
        self.hMiddle.addLayout(self.vEditors)
        self.vMain.addLayout(self.hMiddle)
        self.hBottom = QtWidgets.QHBoxLayout()
        self.hBottom.setObjectName("hBottom")
        self.btnConfirmOwnDiff = QtWidgets.QPushButton(parent=OverigPanel)
        self.btnConfirmOwnDiff.setObjectName("btnConfirmOwnDiff")
        self.hBottom.addWidget(self.btnConfirmOwnDiff)
        self.btnBackToMain = QtWidgets.QPushButton(parent=OverigPanel)
        self.btnBackToMain.setObjectName("btnBackToMain")
        self.hBottom.addWidget(self.btnBackToMain)
        self.lblOwnDiffStatus = QtWidgets.QLabel(parent=OverigPanel)
        self.lblOwnDiffStatus.setObjectName("lblOwnDiffStatus")
        self.hBottom.addWidget(self.lblOwnDiffStatus)
        self.vMain.addLayout(self.hBottom)

        self.retranslateUi(OverigPanel)
        QtCore.QMetaObject.connectSlotsByName(OverigPanel)

# [END: setupUi]
logger.debug("retranslateUi() called")
# [FUNC: retranslateUi]
    def retranslateUi(self, OverigPanel):
        _translate = QtCore.QCoreApplication.translate
        OverigPanel.setWindowTitle(_translate("OverigPanel", "Overig – Diff viewer"))
        self.btnPrevDiff.setText(_translate("OverigPanel", "Vorige verschil"))
        self.btnNextDiff.setText(_translate("OverigPanel", "Volgende verschil"))
        self.chkShowOnlyDiffs.setText(_translate("OverigPanel", "Toon enkel verschillen"))
        self.chkIgnoreWhitespace2.setText(_translate("OverigPanel", "Negeer witruimte"))
        self.chkIgnoreCase2.setText(_translate("OverigPanel", "Negeer hoofdletters"))
        self.txtSearch.setPlaceholderText(_translate("OverigPanel", "Zoek..."))
        self.btnSearch.setText(_translate("OverigPanel", "Zoek"))
        self.lblBlockContext.setText(_translate("OverigPanel", "(context)"))
        self.btnConfirmOwnDiff.setText(_translate("OverigPanel", "Bevestig (save temp1)"))
        self.btnBackToMain.setText(_translate("OverigPanel", "Terug"))
        self.lblOwnDiffStatus.setText(_translate("OverigPanel", "Status: gereed"))
# [END: Ui_OverigPanel]
# [END: retranslateUi]
