# Form implementation generated from reading ui file 'C:\OneDrive\Vioprint\OneDrive - Vioprint\software projecten\Projectassisten2_0\gui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


# [SECTION: Imports]
import logging
from PyQt6 import QtCore, QtGui, QtWidgets
logger = logging.getLogger(__name__)


# [END: Imports]
# [CLASS: Ui_MainWindow]
class Ui_MainWindow(object):
# [FUNC: setupUi]
logger.debug("setupUi() called")
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setMinimumSize(QtCore.QSize(700, 500))
        MainWindow.setStyleSheet("\n"
"QGroupBox {\n"
"  font-weight: bold;\n"
"  border: 1px solid #444;\n"
"  border-radius: 6px;\n"
"  margin-top: 10px;\n"
"}\n"
"QGroupBox::title {\n"
"  subcontrol-origin: margin;\n"
"  left: 10px;\n"
"  padding: 0 4px;\n"
"}\n"
"QPushButton { padding: 6px 10px; }\n"
"QLineEdit, QTextEdit { padding: 4px; }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.grpNewProject = QtWidgets.QGroupBox(parent=MainWindow)
        self.grpNewProject.setObjectName("grpNewProject")
        self.gridNewProject = QtWidgets.QGridLayout(self.grpNewProject)
        self.gridNewProject.setObjectName("gridNewProject")
        self.label = QtWidgets.QLabel(parent=self.grpNewProject)
        self.label.setObjectName("label")
        self.gridNewProject.addWidget(self.label, 0, 0, 1, 1)
        self.ShowProjectFolder = QtWidgets.QLineEdit(parent=self.grpNewProject)
        self.ShowProjectFolder.setReadOnly(True)
        self.ShowProjectFolder.setObjectName("ShowProjectFolder")
        self.gridNewProject.addWidget(self.ShowProjectFolder, 0, 1, 1, 1)
        self.SelectPrjocetFolder = QtWidgets.QPushButton(parent=self.grpNewProject)
        self.SelectPrjocetFolder.setObjectName("SelectPrjocetFolder")
        self.gridNewProject.addWidget(self.SelectPrjocetFolder, 0, 2, 1, 1)
        self.Label02 = QtWidgets.QLabel(parent=self.grpNewProject)
        self.Label02.setObjectName("Label02")
        self.gridNewProject.addWidget(self.Label02, 1, 0, 1, 1)
        self.NewProjectNameEdit = QtWidgets.QLineEdit(parent=self.grpNewProject)
        self.NewProjectNameEdit.setObjectName("NewProjectNameEdit")
        self.gridNewProject.addWidget(self.NewProjectNameEdit, 1, 1, 1, 2)
        self.lblReadme = QtWidgets.QLabel(parent=self.grpNewProject)
        self.lblReadme.setObjectName("lblReadme")
        self.gridNewProject.addWidget(self.lblReadme, 2, 0, 1, 3)
        self.READmeBox = QtWidgets.QTextEdit(parent=self.grpNewProject)
        self.READmeBox.setObjectName("READmeBox")
        self.gridNewProject.addWidget(self.READmeBox, 3, 0, 1, 3)
        self.verticalLayout.addWidget(self.grpNewProject)
        self.layoutButtons = QtWidgets.QHBoxLayout()
        self.layoutButtons.setObjectName("layoutButtons")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutButtons.addItem(spacerItem)
        self.StartCreateProject = QtWidgets.QPushButton(parent=MainWindow)
        self.StartCreateProject.setObjectName("StartCreateProject")
        self.layoutButtons.addWidget(self.StartCreateProject)
        self.verticalLayout.addLayout(self.layoutButtons)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

# [END: setupUi]
logger.debug("retranslateUi() called")
# [FUNC: retranslateUi]
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project Creator"))
        self.grpNewProject.setTitle(_translate("MainWindow", "Nieuw project"))
        self.label.setText(_translate("MainWindow", "Projectfolder:"))
        self.SelectPrjocetFolder.setText(_translate("MainWindow", "Bladeren…"))
        self.Label02.setText(_translate("MainWindow", "Nieuwe projectnaam:"))
        self.lblReadme.setText(_translate("MainWindow", "README (optioneel):"))
        self.StartCreateProject.setText(_translate("MainWindow", "Maak project"))
# [END: Ui_MainWindow]
# [END: retranslateUi]
